### ISSUE TITLE
Application crashes when losing internet connection

### ISSUE THREAD

**Issue by mohamedsalah414** [pusher/pusher-channels-flutter#116]
I've noticed that when the application loses connection to the server, it crashes instead of properly handling the error.

I've tried to test the application in different network conditions, and I've made sure that the code is properly handling network errors and lost connections. However, the application still crashes when these events occur.

I used the latest version 
```dart
pusher_channels_flutter: ^2.1.2
``` 

```
E/AndroidRuntime(11143): FATAL EXCEPTION: pusher-java-client eventQueue
E/AndroidRuntime(11143): Process: com.flojics.writx, PID: 11143
E/AndroidRuntime(11143): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.pusher.client.channel.impl.message.AuthResponse.getChannelData()' on a null object reference
E/AndroidRuntime(11143): 	at com.pusher.client.channel.impl.PrivateChannelImpl.authorize(PrivateChannelImpl.java:84)
E/AndroidRuntime(11143): 	at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:101)
E/AndroidRuntime(11143): 	at com.pusher.client.channel.impl.ChannelManager.lambda$sendOrQueueSubscribeMessage$0$com-pusher-client-channel-impl-ChannelManager(ChannelManager.java:134)
E/AndroidRuntime(11143): 	at com.pusher.client.channel.impl.ChannelManager$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime(11143): 	at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:140)
E/AndroidRuntime(11143): 	at com.pusher.client.util.Factory$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(11143): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(11143): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(11143): 	at java.lang.Thread.run(Thread.java:923)
I/Process (11143): Sending signal. PID: 11143 SIG: 9
Lost connection to device. 
```

**Comment by gabrielginter** [comment]
I'm experiencing the same type of crash, this seems to be a real issue right now, here is my error logs from Crashlytics, I got 55 of them in a a period of 1 hour.

Using version `2.1.2` with flutter `3.10.5`

```
Fatal Exception: java.lang.NullPointerException:
       at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.authorize(PusherChannelsFlutterPlugin.java:13)
       at com.pusher.client.channel.impl.PrivateChannelImpl.getAuthorizationResponse(PrivateChannelImpl.java:12)
       at com.pusher.client.channel.impl.PrivateChannelImpl.authorize(PrivateChannelImpl.java:2)
       at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:6)
       at com.pusher.client.channel.impl.ChannelManager.lambda$sendOrQueueSubscribeMessage$0(ChannelManager.java:10)
       at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by benjamin-tang-pusher** [comment]
v2.2.0 Flutter library works around this issue and no longer crashes, so please upgrade to that. I think the underlying Java library is not handling some auth responses well, but I'm not able to reproduce this.
