### ISSUE TITLE
FATAL EXCEPTION: pusher-java-client eventQueue

### ISSUE THREAD

**Issue by LikeshadowsStone** [pusher/pusher-channels-flutter#125]
java.lang.NullPointerException: Attempt to invoke interface method 'com.pusher.client.channel.User com.pusher.client.channel.PresenceChannel.getMe()' on a null object reference
E/AndroidRuntime(26464): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onUsersInformationReceived(PusherChannelsFlutterPlugin.kt:277)
E/AndroidRuntime(26464): 	at com.pusher.client.channel.impl.PresenceChannelImpl.handleSubscriptionSuccessfulMessage(PresenceChannelImpl.java:131)
E/AndroidRuntime(26464): 	at com.pusher.client.channel.impl.PresenceChannelImpl.handleEvent(PresenceChannelImpl.java:65)
E/AndroidRuntime(26464): 	at com.pusher.client.channel.impl.ChannelManager.handleEvent(ChannelManager.java:107)
E/AndroidRuntime(26464): 	at com.pusher.client.Pusher.handleEvent(Pusher.java:111)
E/AndroidRuntime(26464): 	at com.pusher.client.Pusher.$r8$lambda$UUaYaB2j6jj3zQqQzZlqZZrsfuE(Unknown Source:0)
E/AndroidRuntime(26464): 	at com.pusher.client.Pusher$$ExternalSyntheticLambda0.accept(Unknown Source:4)
E/AndroidRuntime(26464): 	at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:163)
E/AndroidRuntime(26464): 	at com.pusher.client.connection.websocket.WebSocketConnection.lambda$onMessage$5$com-pusher-client-connection-websocket-WebSocketConnection(WebSocketConnection.java:212)
E/AndroidRuntime(26464): 	at com.pusher.client.connection.websocket.WebSocketConnection$$ExternalSyntheticLambda7.run(Unknown Source:4)
E/AndroidRuntime(26464): 	at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:140)
E/AndroidRuntime(26464): 	at com.pusher.client.util.Factory$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(26464): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(26464): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(26464): 	at java.lang.Thread.run(Thread.java:920)
I/Process (26464): Sending signal. PID: 26464 SIG: 9
Lost connection to device.

**Comment by LikeshadowsStone** [comment]
I found a solution for myself here 
https://github.com/pusher/pusher-channels-flutter/issues/43
set the onXXX callback in subscribe() rather than init()
