### ISSUE TITLE
PusherChannelsFlutterPlugin.authorize Firebase Crashlytics

### ISSUE THREAD

**Issue by canibal1** [pusher/pusher-channels-flutter#129]
Hey,

I'm getting this error in Firebase Crashlytics dashboard, but it doesn't come when I debug. Does anyone know why this error is coming?

Fatal Exception: java.lang.NullPointerException:
       at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.authorize(PusherChannelsFlutterPlugin.java:13)
       at com.pusher.client.channel.impl.PrivateChannelImpl.getAuthorizationResponse(PrivateChannelImpl.java:12)
       at com.pusher.client.channel.impl.PrivateChannelImpl.authorize(PrivateChannelImpl.java:2)
       at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:6)
       at com.pusher.client.channel.impl.PresenceChannelImpl.toSubscribeMessage(PresenceChannelImpl.java)
       at com.pusher.client.channel.impl.ChannelManager.lambda$sendOrQueueSubscribeMessage$0(ChannelManager.java:10)
       at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

<img width="2267" alt="Screenshot 2023-09-05 at 16 17 47" src="https://github.com/pusher/pusher-channels-flutter/assets/25279532/d156e4cd-3381-4d96-9ab5-cf70e79fef09">
<img width="1447" alt="Screenshot 2023-09-05 at 16 17 59" src="https://github.com/pusher/pusher-channels-flutter/assets/25279532/428650ee-ce4d-454f-a4b8-20a4ace12e05">

**Comment by benw-pusher** [comment]
Are you able to share the code in use? 
Is the auth endpoint accessible from the device?

**Comment by canibal1** [comment]
This is onAuthorizer function. I test but it's works very well. But some users get crush.


<img width="1258" alt="Screenshot 2023-09-05 at 17 10 28" src="https://github.com/pusher/pusher-channels-flutter/assets/25279532/192a62ab-e745-4f83-9657-3816e302e473">

**Comment by canibal1** [comment]
@benw-pusher  if you want I can share other code in use about pusher. But I think everything is same like example project.

**Comment by benw-pusher** [comment]
Can you clarify: does this only occur in production, when testing you don't see this?

**Comment by canibal1** [comment]
It was occur in the production. No, when I test it in the debug mode I never see it.

**Comment by benw-pusher** [comment]
Thanks for confirming. This suggests there is a difference in the response received between your test and your prod setups - which is also suggested by the stack trace showing the error at '`getAuthorizationResponse`. Are you able to share the responses from each environment? 
Or there could be an inability to access the auth endpoint in prod, or a specifiec variable/parameter is not being passed/set .

**Comment by benw-pusher** [comment]
We haven't had a response here so will close. If you need further support pease get in touch at https://messagebird.com/support-center/Pusher-request-new
