### ISSUE TITLE
Crash on android 6.0.1 (100%) - Pusher.<init> java.lang.NoClassDefFoundError - ma.d

### ISSUE THREAD

**Issue by hautvfami** [pusher/pusher-channels-flutter#132]
Crash logs
```
Fatal Exception: java.lang.NoClassDefFoundError: ma.d
       at com.pusher.client.Pusher.<init>(Pusher.java)
       at com.pusher.client.Pusher.<init>(Pusher.java)
       at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.init(PusherChannelsFlutterPlugin.java)
       at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onMethodCall(PusherChannelsFlutterPlugin.java)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage()
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Flutter logs
flutter_error_exception | PlatformException(error, null, null, java.lang.NullPointerException at la.c.x() at la.c.onMethodCall() at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage() at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler() at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0() at io.flutter.embedding.engine.dart.DartMessenger.a() at io.flutter.embedding.engine.dart.a.run() at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:7406) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) )
-- | --

Thanks pusher team

**Comment by hautvfami** [comment]
<img width="1257" alt="image" src="https://github.com/pusher/pusher-channels-flutter/assets/21011312/4c0031ed-e109-410c-82d9-60d23317a7b4">

**Comment by benw-pusher** [comment]
I believe there may be an error in our support versions documentation, Android 6 may not be supported by default and additional steps are required to function on Android 6 devices. 
Are you able to follow the desugaring guidance at https://developer.android.com/studio/write/java8-support#library-desugaring and let me know if this resolves the issue? Note that the instructions are for native Android applications, but you should still be able to update the dependencies as required. 

Do you see the same crashes on Android 7?

**Comment by benw-pusher** [comment]
We've not had a response here so I'll close this, if you need further support please get in touch at https://support.pusher.com/hc/en-us/requests/new

**Comment by aggeloskoutanis** [comment]
I am facing the same problem. it would be nice if there were some steps on how to fix this
