### ISSUE TITLE
Presence channel Android - FATAL EXCEPTION: pusher-java-client eventQueue

### ISSUE THREAD

**Issue by OlrikNijmeijer** [pusher/pusher-channels-flutter#43]
We are integrating this package, and everything worked fine on ios devices.
When I tried to run the app on android, I keep getting the following exception and the app shuts down.

```
E/AndroidRuntime( 8593): FATAL EXCEPTION: pusher-java-client eventQueue
E/AndroidRuntime( 8593): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.pusher.client.channel.User.getId()' on a null object reference
E/AndroidRuntime( 8593): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onUsersInformationReceived(PusherChannelsFlutterPlugin.kt:272)
E/AndroidRuntime( 8593): 	at com.pusher.client.channel.impl.PresenceChannelImpl.handleSubscriptionSuccessfulMessage(PresenceChannelImpl.java:126)
E/AndroidRuntime( 8593): 	at com.pusher.client.channel.impl.PresenceChannelImpl.onMessage(PresenceChannelImpl.java:58)
E/AndroidRuntime( 8593): 	at com.pusher.client.channel.impl.ChannelManager.onMessage(ChannelManager.java:116)
E/AndroidRuntime( 8593): 	at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:177)
E/AndroidRuntime( 8593): 	at com.pusher.client.connection.websocket.WebSocketConnection.access$600(WebSocketConnection.java:27)
E/AndroidRuntime( 8593): 	at com.pusher.client.connection.websocket.WebSocketConnection$6.run(WebSocketConnection.java:261)
E/AndroidRuntime( 8593): 	at com.pusher.client.util.Factory$1.run(Factory.java:119)
E/AndroidRuntime( 8593): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 8593): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 8593): 	at java.lang.Thread.run(Thread.java:923)
```

This only happens on android when subscribing to a presence channel.
In the 'onAuthorizer' function we do a request to our api which returns the socket_auth(or presence_auth) function from the pusher laravel package.

How can we solve this issue?

**Comment by pwnywiz** [comment]
Im experiencing the same issue, but, does the `onAuthorizer` even get called? I think it crashes right after trying to subscribe.

**Comment by OlrikNijmeijer** [comment]
The onAuthorizer is called in my application. But after this, it crashes.

**Comment by petodavid** [comment]
Same issue, did you find a solution?

**Comment by petodavid** [comment]
```
E/AndroidRuntime( 5696): FATAL EXCEPTION: pusher-java-client eventQueue
E/AndroidRuntime( 5696): Process: com.pravera.flutter_foreground_task_example, PID: 5696
E/AndroidRuntime( 5696): java.lang.NullPointerException
E/AndroidRuntime( 5696): 	at e.c.a.c.m(:90)
E/AndroidRuntime( 5696): 	at e.c.a.c.a(:209)
E/AndroidRuntime( 5696): 	at e.c.b.f.f.b$d.run(:166)
E/AndroidRuntime( 5696): 	at e.c.b.h.b$a.run(:119)
E/AndroidRuntime( 5696): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 5696): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 5696): 	at java.lang.Thread.run(Thread.java:920)
```

**Comment by OlrikNijmeijer** [comment]
I haven't found a solution yet, i think the issue is in the package and needs to be fixed.
Also noticed that private channels where only fixed in v.1.0.5 so i hope the presence channels will be fixed in v.1.0.6...

**Comment by proggen-com** [comment]
It seems the plugin crashes here:

PusherChannelsFlutterPlugin.kt 272:    "userId" to channel.me.id

Is it possible you set a breakpoint there in Android Studio, and see what is in the "me" member?

**Comment by shubhrajyotidey305** [comment]
I am stuck at the same problem, is there any solution available?

**Comment by shubhrajyotidey305** [comment]
I happened to find a solution for Presence-Channel subscription for this package. 
It works for both Android and Web.

All you have to do is declare your `channelName`, `onSubscriptionSucceeded()`, `onEvent()`, `onSubscriptionError()` under the `pusher.subscribe()` rather than declare it under `pusher.init()`. And for the server-side, you must provide `user_id` and `user_info
` to `pusher.authenticate()`.

I am attaching my code on the `flutter-side` and `server-side` (I used a `nodeJs` server).

`1. flutter `

```
import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart';
import 'package:pusher_channels_flutter/pusher_channels_flutter.dart';
import 'secrets.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static PusherChannelsFlutter pusher = PusherChannelsFlutter.getInstance();
  String userName = 'Anonymous';
  String get authURL => "${_hostname()}/pusher/auth/$userName";
  String channelName = 'presence-my-channel';

  Future<void> _initPusher() async {
    try {
      await pusher.init(
        apiKey: apikey, // Place Your own Api Key
        cluster: cluster, // Place Your own Cluster
        onConnectionStateChange: onConnectionStateChange,
        onAuthorizer: onAuthorizer,
        useTLS: true,
        authEndpoint: authURL,
      );

      await pusher.subscribe(
        channelName: channelName,
        onSubscriptionSucceeded: (data) {
          onSubscriptionSucceeded(channelName, data);
        },
        onSubscriptionError: (message, e) {
          onSubscriptionError(message, e);
        },
        onEvent: (event) {
          onEvent(event);
        },
      );
      await pusher.connect();
    } catch (e) {
      if (kDebugMode) {
        print("Error: $e");
      }
    }
  }

  void onConnectionStateChange(dynamic currentState, dynamic previousState) {
    if (kDebugMode) {
      print("Connection: $currentState");
    }
  }

  String _hostname() {
    if (kIsWeb) {
      return 'http://localhost:5000';
    } else {
      if (Platform.isAndroid) {
        return 'http://10.0.2.2:5000';
      } else {
        return 'http://localhost:5000';
      }
    }
  }

  dynamic onAuthorizer(
      String channelName, String socketId, dynamic options) async {
    var result = await post(
      Uri.parse(authURL),
      headers: {"Content-Type": "application/x-www-form-urlencoded"},
      body: {
        "socket_id": socketId,
        "channel_name": channelName,
      },
    );
    return jsonDecode(result.body);
  }

  void onSubscriptionSucceeded(String channelName, dynamic data) {
    if (kDebugMode) {
      print("onSubscriptionSucceeded: $channelName data: $data");
    }
  }

  void onSubscriptionError(String message, dynamic e) {
    if (kDebugMode) {
      print("onSubscriptionError: $message Exception: $e");
    }
  }

  void onEvent(PusherEvent event) {
    if (kDebugMode) {
      print("Event Received: ${event.data}");
      print("Event name: ${event.eventName}");
    }
  }

  @override
  void initState() {
    super.initState();
    _initPusher();
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```

**Note:**  Add this below code in flutter-side Web 

```
<head>
  <script
    charset="utf-8"
    src="https://js.pusher.com/7.0/pusher.min.js"
  ></script>
  ...
</head>
```

`2. server (nodeJs)`

```
// First install the dependencies:
// npm install pusher express cors

const express = require("express");
const cors = require("cors");
const Pusher = require("pusher");
const pusher = new Pusher({
  appId: "APP_ID",
  key: "APP_KEY",
  secret: "APP_SECRET",
  cluster: "APP_CLUSTER",
  useTLS: true,
});
const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cors());
app.post("/pusher/auth/:id", function (req, res) {
  const socketId = req.body.socket_id
  const channel_name = req.body.channel_name
  const presenceData = {
    user_id: req.params.id,
    user_info: { id: req.params.id},
  };
  const authResponse = pusher.authenticate(socketId, channel_name, presenceData);
  console.log('server auth', authResponse)
  res.send(authResponse);
})

const port = process.env.PORT || 5000;
app.listen(port);
```

**Hope it helps!**

**Comment by benw-pusher** [comment]
Hi @OlrikNijmeijer does the solution posted above help? If not, could you share the code you are using for subscribing to the channel and the version in use?

**Comment by KestasVenslauskas** [comment]
My issue was that I tried to use multiple repositories which called "connect()" on the pusher channels plugin.
Fixed by having single connection handler

**Comment by kaushikparmar** [comment]
Thanks @shubhrajyotidey305 

I just removed following callbacks and kept onAuthorized only in init() and it works fine.

**Comment by ebabhi** [comment]
**In my case, I had not decoded the value.**
```
  Future<dynamic> _authorizeChannel(
      String channelName, String socketId, dynamic options) async {
    final response = await dio.post(
      '/user/pusher/channel-auth',
      data: {
        'socket_id': socketId,
        'channel_name': channelName,
      },
    );
    return response.data;
  }
```

**Fixed it By**

```
  Future<dynamic> _authorizeChannel(
      String channelName, String socketId, dynamic options) async {
    final response = await dio.post(
      '/user/pusher/channel-auth',
      data: {
        'socket_id': socketId,
        'channel_name': channelName,
      },
    );
    return jsonDecode(response.data);
  }
```
