### ISSUE TITLE
Channel name is invalid error

### ISSUE THREAD

**Issue by samclam** [pusher/pusher-channels-flutter#59]
When  i am subscribing new private encrypted channel facing below error.

**Error**
````
I/PusherChannelsFlutter(14182): Start com.pusher.client.Pusher@4140054
E/MethodChannel#pusher_channels_flutter(14182): Failed to handle method call
E/MethodChannel#pusher_channels_flutter(14182): java.lang.IllegalArgumentException: Channel name private-encrypted-my-channel is invalid. Private channel names must start with "private-" and presence channel names must start with "presence-"
E/MethodChannel#pusher_channels_flutter(14182): 	at com.pusher.client.channel.impl.ChannelImpl.<init>(ChannelImpl.java:37)
E/MethodChannel#pusher_channels_flutter(14182): 	at com.pusher.client.channel.impl.PrivateChannelImpl.<init>(PrivateChannelImpl.java:30)
E/MethodChannel#pusher_channels_flutter(14182): 	at com.pusher.client.util.Factory.newPrivateChannel(Factory.java:88)
E/MethodChannel#pusher_channels_flutter(14182): 	at com.pusher.client.Pusher.subscribePrivate(Pusher.java:283)
E/MethodChannel#pusher_channels_flutter(14182): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.subscribe(PusherChannelsFlutterPlugin.kt:143)
E/MethodChannel#pusher_channels_flutter(14182): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onMethodCall(PusherChannelsFlutterPlugin.kt:68)
E/MethodChannel#pusher_channels_flutter(14182): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#pusher_channels_flutter(14182): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#pusher_channels_flutter(14182): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#pusher_channels_flutter(14182): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
E/MethodChannel#pusher_channels_flutter(14182): 	at android.os.Handler.handleCallback(Handler.java:751)
E/MethodChannel#pusher_channels_flutter(14182): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/MethodChannel#pusher_channels_flutter(14182): 	at android.os.Looper.loop(Looper.java:154)
E/MethodChannel#pusher_channels_flutter(14182): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/MethodChannel#pusher_channels_flutter(14182): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#pusher_channels_flutter(14182): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/MethodChannel#pusher_channels_flutter(14182): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/flutter (14182): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, Channel name private-encrypted-my-channel is invalid. Private channel names must start with "private-" and presence channel names must start with "presence-", null, java.lang.IllegalArgumentException: Channel name private-encrypted-my-channel is invalid. Private channel names must start with "private-" and presence channel names must start with "presence-"
E/flutter (14182): 	at com.pusher.client.channel.impl.ChannelImpl.<init>(ChannelImpl.java:37)
E/flutter (14182): 	at com.pusher.client.channel.impl.PrivateChannelImpl.<init>(PrivateChannelImpl.java:30)
E/flutter (14182): 	at com.pusher.client.util.Factory.newPrivateChannel(Factory.java:88)
E/flutter (14182): 	at com.pusher.client.Pusher.subscribePrivate(Pusher.java:283)
E/flutter (14182): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.subscribe(PusherChannelsFlutterPlugin.kt:143)
E/flutter (14182): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onMethodCall(PusherChannelsFlutterPlugin.kt:68)
E/flutter (14182): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (14182): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (14182): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/flutter (14182): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
E/flutter (14182): 	at android.os.Handler.handleCallback(Handler.java:751)
E/flutter (14182): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/flutter (14182): 	at android.os.Looper.loop(Looper.java:154)
E/flutter (14182): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/flutter (14182): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14182): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/flutter (14182): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/flutter (14182): )
E/flutter (14182): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (14182): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (14182): <asynchronous suspension>
E/flutter (14182): #2      PusherChannelsFlutter.subscribe (package:pusher_channels_flutter/pusher_channels_flutter.dart:237:5)
E/flutter (14182): <asynchronous suspension>
E/flutter (14182): #3      Pusher._init (package:zifhy_app/pusher/pusher_file.dart:58:5)
E/flutter (14182): <asynchronous suspension>
E/flutter (14182): `

```

**Comment by devansvd** [comment]
For Private channel it is working fine. Facing the above issue with private-encrypted-channel

**Comment by benw-pusher** [comment]
I've been able to replicate this issue and have raised an issue with our Engineering team to investigate. I will let you know when we have an update on this.

**Comment by macpraveen** [comment]
Just have to swap the switch case. Refer this,
https://github.com/macpraveen/pusher-channels-flutter/commit/9a07d94d00a9764cffad6671efe61b1ad19afb07

I can give a PR if needed.
