### ISSUE TITLE
Exception java.lang.NoClassDefFoundError:   at com.pusher.client.Pusher.<init> (Pusher.java)  

### ISSUE THREAD

**Issue by Ibrahim20300** [pusher/pusher-channels-flutter#93]
I received this  exception from some users in google play console

Exception java.lang.NoClassDefFoundError:
  at com.pusher.client.Pusher.<init> (Pusher.java)
  at com.pusher.client.Pusher.<init> (Pusher.java)
  at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.init (PusherChannelsFlutterPlugin.java)
  at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onMethodCall (PusherChannelsFlutterPlugin.java)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java)
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java)
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0 (DartMessenger.java)
  at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$TsixYUB5E6FpKhMtCSQVHKE89gQ (DartMessenger.java)
  at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$ceffc6bae7d364cb48afaf1aaebd60bf9050360d0efb9035ebc54f0851df0a05$0.run (DartMessenger.java)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:6134)
  at java.lang.reflect.Method.invoke (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1399)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)

So how can i fix this problem ?

**Comment by luisfelipeas5** [comment]
This is happening here too.

And I have something to add: 90% of the devices with this issue has version = Android 6  (API level 23) and the other 10% has Android 5

![Screenshot 2023-01-26 at 09 12 58](https://user-images.githubusercontent.com/11656791/214832484-01885b74-c669-4f92-93c1-72077b5b1cb3.png)

Since we implemented Pusher Channels, we had 441 crash events

**Comment by paramaw** [comment]
I have the same exact issue on Android 6.

**Comment by paramaw** [comment]
> This is happening here too.
> 
> And I have something to add: 90% of the devices with this issue has version = Android 6 (API level 23) and the other 10% has Android 5
> 
> ![Screenshot 2023-01-26 at 09 12 58](https://user-images.githubusercontent.com/11656791/214832484-01885b74-c669-4f92-93c1-72077b5b1cb3.png)
> 
> Since we implemented Pusher Channels, we had 441 crash events

I have the same exact issue on Android 6

**Comment by paramaw** [comment]
Seems like downgrading it to v1.0.5 solved the issue.

**Comment by eebrahimjoy** [comment]
**App crashed when going to connect pusher channel. 
Android 6. API Level - 23**

`E/AndroidRuntime(12553): java.lang.NoClassDefFoundError: com.pusher.client.Pusher$$ExternalSyntheticLambda0
E/AndroidRuntime(12553): 	at com.pusher.client.Pusher.<init>(Pusher.java:103)
E/AndroidRuntime(12553): 	at com.pusher.client.Pusher.<init>(Pusher.java:85)
E/AndroidRuntime(12553): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.init(PusherChannelsFlutterPlugin.kt:122)
E/AndroidRuntime(12553): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onMethodCall(PusherChannelsFlutterPlugin.kt:65)
E/AndroidRuntime(12553): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime(12553): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(12553): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(12553): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/AndroidRuntime(12553): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(12553): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12553): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(12553): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime(12553): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12553): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(12553): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by benw-pusher** [comment]
As this issue appears to be affecting older version of Android have you looked into [desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring)? 
I've tried to replicate this but I am having other issues with getting emulated devices with old Android versions to run correctly on my m1 machine.
