### ISSUE TITLE
java.lang.NullPointerException when app is in the background

### ISSUE THREAD

**Issue by paramaw** [pusher/pusher-channels-flutter#96]
I'm getting this issue, does anyone here know how to do fix this?

```
Fatal Exception: java.lang.NullPointerException:
       at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.callback(PusherChannelsFlutterPlugin.java:2)
       at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onConnectionStateChange(PusherChannelsFlutterPlugin.java:48)
       at com.pusher.client.connection.websocket.WebSocketConnection$4.run(WebSocketConnection.java:4)
       at com.pusher.client.util.Factory$1.run(Factory.java:7)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```
       
     
According to crashlytics this is happening when the app is in the background.

[stacktrace.txt](https://github.com/pusher/pusher-channels-flutter/files/10712126/issue_9fa6c00950d2d91e01c1af94ae31deb4_crash_session_63E6CC7A02B2000244D12016C9D69166_DNE_0_v2_stacktrace.txt)

**Comment by benjamin-tang-pusher** [comment]
Hi, this is the same issue as https://github.com/pusher/pusher-channels-flutter/issues/91. Other customers have also gotten the same crashlytics errors from their clients, but as I haven't been able to reproduce this on my device we have not been able to fix the root cause of the Activity becoming Null.

If you upgrade the flutter library to 2.1.2, we've implemented a workaround that stops the app from crashing, although I'm still interested to hear if the app stops receiving messages afterwards.
